services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: react-flask-app-server
    networks:
      - app-network
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    networks:
      - app-network
    ports:
      - "3000:3000"
networks:
  app-network:
    driver: bridge