FROM python:3.9
WORKDIR /app

COPY server/ ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV development
ENV PYTHONPATH /app

EXPOSE 8080
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080"]