FROM python:3.9

WORKDIR /app

COPY server/ ./

RUN pip install -r ./requirements.txt

# Set environment variables
ENV FLASK_ENV=production

EXPOSE 8080

# Use Gunicorn to serve the app
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:create_app()"]
